# Generated by Django 4.0.5 on 2022-08-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_is_delete_blog_updated_alter_blog_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
