# Generated by Django 4.0.5 on 2022-08-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment_is_hidden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_hidden',
            new_name='is_delete',
        ),
    ]
